[package]
name = "ledger-bitcoin-client"
version = "0.5.0"
edition = "2021"
description = "Fork of ledger_bitcoin_client (https://github.com/LedgerHQ/app-bitcoin-new) with async removed"
license = "Apache-2.0"

[dependencies]
bitcoin = { version = "0.32", default-features = false }
miniscript = { version = "12.2", features = ["no-std"], optional = true, default-features = false }

[features]
paranoid_client = ["miniscript"]
default = ["paranoid_client"]
