[workspace]
resolver = "2"

members = [
    "bwk",
    "sp",
    "electrum",
    "backoff",
    "keys", "utils", "sign", "descriptor", "tx",
    "p2p",
]

[workspace.package]
edition = "2021"
authors = ["pythcoiner"]
license-file = "LICENSE"
repository = "https://github.com/pythcoiner/bwk"
keywords = ["bitcoin"]
readme = "README.md"

[workspace.dependencies]
base64ct = "=1.6.0"
url = "=2.5.2"
bip39 = "2.2.0"
bitcoin = "0.32.0"
bitcoin_slices = "0.8.0"
dirs = "6.0.0"
hex = "0.4"
hex-conservative = "0.2.1"
hex_lit = "0.1.1"
home = "=0.5.9"
libc = "0.2.170"
log = "0.4.20"
miniscript = "12.2.0"
native-tls = "=0.2.13"
openssl = "0.10.66"
rand = "0.9.1"
serde = "1.0.218"
serde_json = "1.0.128"
env_logger = "0.11.6"
temp-dir = "0.1.16"
thiserror = "2.0.0"
ureq = { version = "2.10", default-features = false }
getrandom = "0.2"
corepc-node = { version = "0.10.0", features = ["download", "29_0"] }
dns-lookup = "2.0"

# spdk dependencies
spdk-core = { git = "https://github.com/pythcoiner/spdk.git", rev = "28b6719", default-features = false }
backend-blindbit-native-non-async = { git = "https://github.com/pythcoiner/spdk.git", rev = "28b6719" }
silentpayments = { git = "https://github.com/pythcoiner/rust-silentpayments.git", branch = "secp_29" }
blindbitd = { git = "https://github.com/pythcoiner/blindbitd.git" }

# bwk crates
bwk-electrum = { path = "electrum" }
bwk-backoff = { path = "backoff" }
bwk-keys = { path = "keys" }
bwk-tx = { path = "tx" }
bwk-sign = { path = "sign" }
bwk-descriptor = { path = "descriptor" }
bwk-utils = { path = "utils" }
bwk-p2p = { path = "p2p" }
bwk = { path = "bwk" }


