[workspace]
resolver = "2"

members = [
    "bwk",
    "sp",
    "electrum",
    "backoff",
    "keys", "utils", "sign", "descriptor", "tx",
    "p2p",
]

[workspace.package]
edition = "2021"
authors = ["pythcoiner"]
license-file = "LICENSE"
repository = "https://github.com/pythcoiner/bwk"
keywords = ["bitcoin"]
readme = "README.md"

[workspace.dependencies]
crossbeam = "0.8"
async-hwi = { version = "0.0.30", default-features = false }
tokio = { version = "1.21", features = ["rt-multi-thread"] }
base64ct = "=1.6.0"
url = "=2.5.2"
bip39 = "2.2.0"
bitcoin = { git = "https://github.com/pythcoiner/rust-bitcoin.git", rev = "d7998651", features = ["serde"] }
bitcoin_slices = "0.8.0"
dirs = "6.0.0"
hex = "0.4"
hex-conservative = "0.2.1"
hex_lit = "0.1.1"
home = "=0.5.9"
libc = "0.2.170"
log = "0.4.20"
miniscript = { version = "12.2.0", features = ["base64"] }
native-tls = "=0.2.13"
openssl = "0.10.66"
rand = "0.9.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.128"
env_logger = "0.11.6"
temp-dir = "0.1.16"
thiserror = "2.0.0"
getrandom = "0.2"
corepc-node = { git = "https://github.com/pythcoiner/corepc.git", branch = "bip375", features = ["download", "29_0"] }
dns-lookup = "2.0"

# spdk dependencies
spdk-core = { git = "https://github.com/pythcoiner/spdk.git", rev = "f00f559", default-features = false }
backend-blindbit-native-non-async = { git = "https://github.com/pythcoiner/spdk.git", rev = "f00f559" }
silentpayments = { git = "https://github.com/pythcoiner/rust-silentpayments.git", branch = "secp_29" }
blindbitd = { git = "https://github.com/pythcoiner/blindbitd.git" }

# bwk crates
bwk-electrum = { path = "electrum" }
bwk-backoff = { path = "backoff" }
bwk-keys = { path = "keys" }
bwk-tx = { path = "tx" }
bwk-sign = { path = "sign" }
bwk-descriptor = { path = "descriptor" }
bwk-utils = { path = "utils" }
bwk-p2p = { path = "p2p" }
bwk = { path = "bwk" }

[patch.crates-io]
bitcoin = { git = "https://github.com/pythcoiner/rust-bitcoin.git", rev = "d7998651" }
corepc-types = { git = "https://github.com/pythcoiner/corepc.git", branch = "bip375" }
corepc-client = { git = "https://github.com/pythcoiner/corepc.git", branch = "bip375" }
corepc-node = { git = "https://github.com/pythcoiner/corepc.git", branch = "bip375" }
