[workspace]
resolver = "3"

members = [
    "bwk",
    "sp",
    "electrum",
    "backoff",
    "keys", "utils", "sign", "descriptor", "tx",
    "persist",
    "p2p",
    "hwi", "hwi/cli",
    "hwi/ledger-bitcoin-client", "hwi/ledger-transport-hidapi", "hwi/bitbox-api",
]

[workspace.package]
edition = "2021"
rust-version = "1.85"
authors = ["pythcoiner"]
license-file = "LICENSE"
repository = "https://github.com/pythcoiner/bwk"
keywords = ["bitcoin"]
readme = "README.md"

[workspace.dependencies]
crossbeam = "0.8"
bwk-hwi = { path = "hwi", default-features = false }
base64ct = "=1.6.0"
url = "=2.5.2"
bip39 = "2.2.0"
bitcoin = { version = "0.32", features = ["serde"] }
bitcoin_slices = "0.8.0"
dirs = "6.0.0"
hex = "0.4"
hex-conservative = "0.2.1"
hex_lit = "0.1.1"
home = "=0.5.9"
libc = "0.2.170"
log = "0.4.20"
miniscript = { version = "12.2.0", features = ["base64"] }
native-tls = "=0.2.13"
openssl = "0.10.66"
rand = "0.9.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.128"
env_logger = "0.11.6"
temp-dir = "0.1.16"
thiserror = "2.0.0"
getrandom = "0.2"
corepc-node = { version = "0.10", features = ["download", "29_0"] }
dns-lookup = "2.0"

# spdk dependencies
spdk-core = { git = "https://github.com/pythcoiner/spdk.git", rev = "f00f559", default-features = false }
backend-blindbit-native-non-async = { git = "https://github.com/pythcoiner/spdk.git", rev = "f00f559" }
silentpayments = { git = "https://github.com/pythcoiner/rust-silentpayments.git", branch = "secp_29" }
blindbitd = { git = "https://github.com/pythcoiner/blindbitd.git" }

# bwk crates
bwk-electrum = { path = "electrum" }
bwk-backoff = { path = "backoff" }
bwk-keys = { path = "keys" }
bwk-tx = { path = "tx" }
bwk-sign = { path = "sign" }
bwk-descriptor = { path = "descriptor" }
bwk-persist = { path = "persist" }
bwk-utils = { path = "utils" }
bwk-p2p = { path = "p2p" }
bwk = { path = "bwk" }

