[package]
name = "bitbox-api"
version = "0.9.0"
edition = "2021"
description = "Fork of bitbox-api (https://github.com/BitBoxSwiss/bitbox-api-rs) with async removed"

[lib]
name = "bitbox_api"
path = "src/lib.rs"

[features]
usb = ["dep:hidapi"]

[dependencies]
base32 = "0.4"
bitcoin = { version = "0.32", features = ["base64"] }
byteorder = "1.3.2"
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
getrandom = "0.2"
hex = "0.4"
hidapi = { version = "2.3", optional = true }
noise-protocol = "0.2"
noise-rust-crypto = "0.6"
num-bigint = "0.4"
prost = "0.13"
semver = "1.0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
zeroize = "1"

[lints.rust]
unexpected_cfgs = "allow"
