[package]
name = "bwk"
version = "0.0.8"
readme.workspace = true
description = "Bitcoin wallet kit"
documentation = "https://docs.rs/bwk"
license-file.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
exclude = ["tests/**"]

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
doctest = false

[dependencies]
bwk-electrum.workspace = true
bwk-backoff.workspace = true
bwk-keys.workspace = true
bwk-descriptor.workspace = true
bwk-persist.workspace = true
bwk-sign.workspace = true
bwk-utils.workspace = true
bwk-tx.workspace = true

miniscript.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
dirs.workspace = true
bip39 = { workspace = true, features = ["serde", "rand"] }

[dev-dependencies]
bwk-persist = { workspace = true, features = ["test"] }
electrsd = { git = "https://github.com/pythcoiner/electrsd.git", branch = "buffered_logs"}
rand = "0.9.0"
temp-dir.workspace = true

[features]
default = []
sp = []
sqlite = ["bwk-persist/sqlite"]
test = ["bwk-utils/test", "bwk-sign/test", "bwk-tx/test", "bwk-persist/test"]
