[package]
name = "ledger-transport-hidapi"
version = "0.10.0"
edition = "2021"
authors = [
    "Zondax AG <hello@zondax.ch>",
    "Edouard Paris <m@edouard.paris>",
]
description = "Fork of ledger-transport-hid (https://github.com/Zondax/ledger-rs) with async removed"
license = "Apache-2.0"

[dependencies]
byteorder = "1.4"
cfg-if = "1.0.0"
hex = "0.4"
hidapi = { version = "2.4.1", features = ["linux-static-hidraw"], default-features = false }
ledger-apdu = "0.10"
libc = "0.2"
log = "0.4"
thiserror.workspace = true
