[package]
name = "bwk-descriptor"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

[dependencies]
bwk-keys.workspace = true
miniscript.workspace = true
thiserror.workspace = true
