[package]
name = "bwk-sp"
version = "0.1.0"
edition = "2021"

[dependencies]
# spdk dependencies
spdk-core = { workspace = true, features = ["sync", "mnemonic", "bitcoin_32"] }
backend-blindbit-native-non-async = { workspace = true }

# bwk crates
bwk = { workspace = true, features = ["sp"] }
bwk-sign = { workspace = true, features = ["sp"] }
bwk-tx = { workspace = true }

# Bitcoin
bitcoin = { workspace = true }
miniscript = { workspace = true }
silentpayments = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Utilities
thiserror = { workspace = true }
log = { workspace = true }
hex = { workspace = true }

# Random number generation
getrandom = { workspace = true }

[dev-dependencies]
blindbitd = { workspace = true }
bwk-utils = { workspace = true, features = ["test"] }
bwk-sign = { workspace = true, features = ["test"] }
bip39 = { workspace = true }
