[package]
name = "bwk-tx"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

[dependencies]
serde.workspace = true
miniscript.workspace = true
bitcoin.workspace = true
bitcoin.features = ["rand-std"]
rand.workspace = true
bwk-descriptor.workspace = true

# Features dependencies
bwk-sign.workspace = true
bwk-sign.optional = true
bwk-utils.workspace = true
bwk-utils.optional = true

[features]
default = ["test"]
test = ["dep:bwk-sign", "dep:bwk-utils"]
